# Generated by Django 3.0.3 on 2020-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200218_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
