# Generated by Django 3.0.3 on 2020-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('loginId', models.CharField(max_length=50, null=True)),
                ('loginPw', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
    ]
