# Generated by Django 3.0.3 on 2020-02-23 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200223_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 2, 23, 23, 32, 7, 821674), null=True),
        ),
    ]
