# Generated by Django 3.0.3 on 2020-03-01 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200223_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='loginId',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 3, 1, 13, 34, 25, 303411), null=True),
        ),
    ]
