# Generated by Django 3.0.3 on 2020-03-03 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200303_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 3, 3, 23, 28, 39, 762710), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 3, 3, 23, 28, 39, 763308), null=True),
        ),
    ]
