# Generated by Django 3.0.3 on 2020-03-15 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200315_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 21, 43, 51, 680646), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 21, 43, 51, 681454), null=True),
        ),
    ]
